name: Release

on:
  workflow_dispatch:

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git
        uses: actions/checkout@v3
      
      - name: Luacheck        
        uses: lunarmodules/luacheck@v1.1.2

      - name: Setup Node.js environment      
        uses: actions/setup-node@v4.0.2
    
      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: latest

      - name: Install Node Packages
        run: pnpm i
        