name: Release

on:
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git
        uses: actions/checkout@v3
      
      - name: Luacheck        
        uses: lunarmodules/luacheck@v1.1.2

      # Build your Lua package (replace with your build steps)
      - name: Build Lua package
        run: 

      # Create a release tag version (replace with your versioning logic)
          git tag v1.0.0

      - name: Push tag
        run: git push origin v1.0.0

      # Create a release on GitHub
      - name: Create GitHub Release
        uses: nlopes/release-action@v3.1.2
        with:
          tag_name: ${{ github.ref }}
          release_name: Lua Release ${{ github.ref }}
          draft: false
          prerelease: false
          file_glob: path/to/your/lua/package/*.lua  # Replace with your package location
